export default {
    FAN_CLUB_CREATE_REQUESTED: "FAN_CLUB_CREATE_REQUESTED",
    FAN_CLUBS_FETCH_REQUESTED: "FAN_CLUBS_FETCH_REQUESTED",
    FAN_CLUBS_FETCH_SUCCEEDED: "FAN_CLUBS_FETCH_SUCCEEDED",
    FAN_CLUBS_FETCH_FAILED: "FAN_CLUBS_FETCH_FAILED",
};
