export default {
    ADD_TEAM_TO_FAVORITES: "ADD_TEAM_TO_FAVORITES",
    REMOVE_TEAM_FROM_FAVORITES: "REMOVE_TEAM_FROM_FAVORITES",

    GET_TEAMS_FROM_FAVORITES_REQUESTED: "GET_TEAMS_FROM_FAVORITES_REQUESTED",
    GET_TEAMS_FROM_FAVORITES_SUCCEEDED: "GET_TEAMS_FROM_FAVORITES_SUCCEEDED",
};
