export default {
    FIXTURES_FETCH_REQUESTED: "FIXTURES_FETCH_REQUESTED",
    FIXTURES_FETCH_SUCCEEDED: "FIXTURES_FETCH_SUCCEEDED",
    FIXTURES_FETCH_FAILED: "FIXTURES_FETCH_FAILED",
    CURRENT_FIXTURE_ID_UPDATE: "CURRENT_FIXTURE_ID_UPDATE",
};
