export default {
    HEAD_2_HEAD_FETCH_REQUESTED: "HEAD_2_HEAD_FETCH_REQUESTED",
    HEAD_2_HEAD_FETCH_SUCCEEDED: "HEAD_2_HEAD_FETCH_SUCCEEDED",
    HEAD_2_HEAD_FETCH_FAILED: "HEAD_2_HEAD_FETCH_FAILED",
};
