export default {
    LEAGUE_FETCH_REQUESTED: "LEAGUE_FETCH_REQUESTED",
    LEAGUE_FETCH_SUCCEEDED: "LEAGUE_FETCH_SUCCEEDED",
    LEAGUE_FETCH_FAILED: "LEAGUE_FETCH_FAILED",
    LEAGUE_INDEX_UPDATE: "LEAGUE_INDEX_UPDATE",
};
