export default {
    TEAM_FETCH_REQUESTED: "TEAM_FETCH_REQUESTED",
    TEAM_FETCH_SUCCEEDED: "TEAM_FETCH_SUCCEEDED",
    TEAM_FETCH_FAILED: "TEAM_FETCH_FAILED",
    TEAM_PAGE_INDEX_UPDATE: "TEAM_PAGE_INDEX_UPDATE",
};
