export default {
    REGISTER_REQUESTED: "REGISTER_REQUESTED",
    REGISTER_SUCCEEDED: "REGISTER_SUCCEEDED",
    REGISTER_FAILED: "REGISTER_FAILED",

    LOGIN_REQUESTED: "LOGIN_REQUESTED",
    LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
    LOGIN_FAILED: "LOGIN_FAILED",

    LOGOUT_REQUESTED: "LOGOUT_REQUESTED",
};
