export default {
    FIXTURES_FETCH_REQUESTED: "FIXTURES_FETCH_REQUESTED",
    FIXTURES_FETCH_SUCCEEDED: "FIXTURES_FETCH_SUCCEEDED",
    FIXTURES_FETCH_FAILED: "FIXTURES_FETCH_FAILED",
    FIXTURE_INDEX_UPDATE: "FIXTURE_INDEX_UPDATE",
};
